// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvY9mZe5uRmDALzhKyD8OaaeqFHxYfG3Q',
    appId: '1:623891134664:web:0f3443a434de10c1e8cdfd',
    messagingSenderId: '623891134664',
    projectId: 'final-project-group-1',
    authDomain: 'final-project-group-1.firebaseapp.com',
    storageBucket: 'final-project-group-1.firebasestorage.app',
    measurementId: 'G-TKNYS1WSY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfOXrwHuDVUfZkR5ys70X7pR4D_xEkwE',
    appId: '1:623891134664:android:17d0911f7f5cbfcce8cdfd',
    messagingSenderId: '623891134664',
    projectId: 'final-project-group-1',
    storageBucket: 'final-project-group-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9nmNQybpQKymMJa3Itmbz0QiyIbyu1g',
    appId: '1:623891134664:ios:2fd88ebb6386d4f1e8cdfd',
    messagingSenderId: '623891134664',
    projectId: 'final-project-group-1',
    storageBucket: 'final-project-group-1.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9nmNQybpQKymMJa3Itmbz0QiyIbyu1g',
    appId: '1:623891134664:ios:2fd88ebb6386d4f1e8cdfd',
    messagingSenderId: '623891134664',
    projectId: 'final-project-group-1',
    storageBucket: 'final-project-group-1.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvY9mZe5uRmDALzhKyD8OaaeqFHxYfG3Q',
    appId: '1:623891134664:web:d5b7ab2a81d36db9e8cdfd',
    messagingSenderId: '623891134664',
    projectId: 'final-project-group-1',
    authDomain: 'final-project-group-1.firebaseapp.com',
    storageBucket: 'final-project-group-1.firebasestorage.app',
    measurementId: 'G-ZPZWG17NM8',
  );
}
